#!/usr/bin/env python3
"""Phase F-R5 XML-only / unpaired key binds. Classifier rules stay frozen."""
from __future__ import annotations

try:
    from tools.parity_phase_f import ProofManifest
except ImportError:
    from parity_phase_f import ProofManifest


def _p(
    proof_id: str,
    keys: tuple[str, ...],
    *,
    a14_path: str,
    a14_symbol: str,
    a13_path: str,
    a13_symbol: str,
    a14_targets: str,
    a13_targets: str,
    ownership: str,
    diff: str,
    api33: str,
    why: str,
    a14_only: str,
    result: str,
    callback: str,
    args: str,
    defaults: str,
    phase14: str = "n/a",
    phase13: str = "n/a",
    installer14: str = "",
    installer13: str = "",
) -> ProofManifest:
    keys_s = ",".join(keys)
    return ProofManifest(
        proof_id=proof_id,
        a14_owner_path=a14_path,
        a14_symbol=a14_symbol,
        a14_installer=installer14 or f"A14 installer/spec gate for {keys_s}",
        a14_hook_targets=a14_targets,
        a14_callback_phase=phase14,
        a13_owner_path=a13_path,
        a13_symbol=a13_symbol,
        a13_installer=installer13 or f"A13 installer gate for {keys_s}",
        a13_hook_targets=a13_targets,
        a13_callback_phase=phase13,
        preference_keys=keys,
        value_domain="owner-local preference domain",
        default_semantics=defaults,
        result_argument_behavior=result,
        api33_variant_reason=api33,
        proof_conclusion="PRESENT_A13_VARIANT",
        evidence_level="INDIVIDUAL_SEMANTIC_PROOF",
        body_relation="REVIEWED_VARIANT",
        diff_summary=diff,
        value_default_comparison=defaults,
        hook_target_comparison=f"A14={a14_targets}; A13={a13_targets}",
        callback_semantics_comparison=callback,
        arg_result_comparison=args,
        a14_only_branches=a14_only,
        why_user_behavior_is_equivalent=why,
        key_ownership_evidence=ownership,
        a14_key_owner_reference=f"{a14_path}::{a14_symbol}",
        a13_key_owner_reference=f"{a13_path}::{a13_symbol}",
    )


def r5_xml_owner_groups() -> list[ProofManifest]:
    return [
        _p(
            "PROOF_R5X_MEDIAPLAYER_APPS",
            ("controls_mediaplayer_apps",),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/utils/feature/SystemServerFeatures.kt",
            a14_symbol="VolumeMediaButtonsFeature / GenericApp volume-media gate",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/installers/GenericAppInstaller.java",
            a13_symbol="needGlobalActions / GenericAppInstaller volume-media",
            a14_targets="(no ROM member; app-selector gate)",
            a13_targets="(no ROM member; app-selector gate)",
            ownership="controls_mediaplayer_apps: LITERAL_READ StringSet in A13 GenericAppInstaller.java and SystemServerInstaller.needGlobalActions; A14 GenericApp/volume-media enabled when the set is non-empty.",
            diff="Both use the app set as a whitelist for screen-off volume-media rewrite. A13 also requires the set non-empty before installing GlobalActions volume hooks.",
            api33="No host member. Same StringSet gate on API33.",
            why="Selected media apps still receive the volume-media key rewrite; empty set still disables it.",
            a14_only="none",
            result="No hook rewrite on this row; it is the selector consumed by VolumeMediaButtonsHook.",
            callback="No Xposed callback on the selector row.",
            args="No setResult. Membership is StringSet.contains(pkg).",
            defaults="Empty set means no media-app rewrite.",
        ),
        _p(
            "PROOF_R5X_DOCKTITLES",
            ("launcher_docktitles",),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/LauncherIconHooks.kt",
            a14_symbol="ShowHotseatTitlesHook",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/LauncherLayoutHooks.kt",
            a13_symbol="ShowHotseatTitlesRes",
            a14_targets="com.miui.home bool config_hide_hotseats_app_title (resource + optional hook)",
            a13_targets="com.miui.home / com.mi.android.globallauncher bool config_hide_hotseats_app_title",
            ownership="launcher_docktitles: INSTALLER_CALLEE A13 LauncherInstaller.java:38 ShowHotseatTitlesRes; A14 LauncherPackageReadyFeatures ShowHotseatTitlesHook.",
            diff="Both force config_hide_hotseats_app_title=false so dock icon titles show. A13 ResourceHooks replacement also covers globallauncher. A14 FeatureSpec calls ShowHotseatTitlesHook.",
            api33="Same Home boolean resource. A13 extra globallauncher package name.",
            why="Dock icon titles still appear when the toggle is on.",
            a14_only="FeatureSpec wrapper name ShowHotseatTitlesHook vs A13 Res helper.",
            result="Resource replacement, not setResult.",
            callback="No Xposed callback required for the bool replacement.",
            args="Replacement value false.",
            defaults="Boolean default false keeps ROM hide-titles.",
            installer13="LauncherInstaller.java getBoolean(launcher_docktitles)",
        ),
        _p(
            "PROOF_R5X_NOCLOCKHIDE",
            ("launcher_noclockhide",),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/LauncherIconHooks.kt",
            a14_symbol="NoClockHideHook",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/LauncherSystemHooks.kt",
            a13_symbol="NoClockHideHook",
            a14_targets="com.miui.home.launcher.Launcher#updateStatusBarClock",
            a13_targets="com.miui.home.launcher.Launcher#updateStatusBarClock",
            ownership="launcher_noclockhide: INSTALLER_CALLEE A13 FeatureCatalog.noClockHide / LauncherInstaller.hasAnyLauncherApplicationFeature; A14 LauncherNoClockHideFeature.",
            diff="Both DO_NOTHING Launcher.updateStatusBarClock so Home cannot hide the status-bar clock.",
            api33="Same Launcher member. A13 file LauncherSystemHooks vs A14 LauncherIconHooks.",
            why="Launcher no longer hides the status-bar clock when the toggle is on.",
            a14_only="none",
            result="Original updateStatusBarClock skipped (DO_NOTHING).",
            callback="Constant skip on both.",
            args="No args. Skip original.",
            defaults="Boolean default false keeps ROM clock-hide.",
        ),
        _p(
            "PROOF_R5X_NOWIDGETONLY",
            ("launcher_nowidgetonly",),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/LauncherLayoutHooks.kt",
            a14_symbol="NoWidgetOnlyHook",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/LauncherLayoutHooks.kt",
            a13_symbol="NoWidgetOnlyHook",
            a14_targets="com.miui.home.launcher.Workspace widget-only mode members",
            a13_targets="com.miui.home.launcher.Workspace widget-only mode members",
            ownership="launcher_nowidgetonly: INSTALLER_CALLEE A13 FeatureCatalog.noWidgetOnly / LauncherInstaller; A14 LauncherNoWidgetOnlyFeature.",
            diff="Both disable Home widget-only workspace restriction via NoWidgetOnlyHook in LauncherLayoutHooks.kt.",
            api33="Same Home owner file. FeatureSpec vs catalog installer.",
            why="Widget-only launcher mode stays disabled when the toggle is on.",
            a14_only="none beyond FeatureSpec wrapper",
            result="Hook skips/forces the ROM widget-only check false.",
            callback="Same owner; intercept vs before adapter.",
            args="Widget-only check result forced off.",
            defaults="Boolean default false keeps ROM widget-only.",
        ),
        _p(
            "PROOF_R5X_PRIVACYAPPS_LIST",
            ("launcher_privacyapps_list",),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/subs/Launcher.kt",
            a14_symbol="privacy apps picker",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/subs/Launcher.kt",
            a13_symbol="onPrivacyAppClick",
            a14_targets="(no ROM member; app-selector UI)",
            a13_targets="(no ROM member; app-selector UI)",
            ownership="launcher_privacyapps_list: settings picker in subs/Launcher.kt on both trees; consumed with launcher_privacyapps_gest by PrivacyFolderHook.",
            diff="Visible row is the privacy-app selector. Hook consumption is PrivacyFolderHook already reviewed.",
            api33="In-module picker, not a host member.",
            why="User still picks which apps belong to the privacy folder.",
            a14_only="none",
            result="No hook on this row.",
            callback="Preference click opens the app selector.",
            args="StringSet persisted for the privacy folder owner.",
            defaults="Empty set means no extra privacy apps.",
        ),
        _p(
            "PROOF_R5X_ANIMATION_SCALE",
            ("system_animationscale_window", "system_animationscale_transition", "system_animationscale_animator"),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/subs/System.kt",
            a14_symbol="Helpers.setAnimationScale",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/subs/System.kt",
            a13_symbol="Helpers.setAnimationScale",
            a14_targets="android.view.IWindowManager#setAnimationScale",
            a13_targets="android.view.IWindowManager#setAnimationScale",
            ownership="LITERAL_READ of the three keys in subs/System.kt SeekBar listeners; both call Helpers.setAnimationScale(0/1/2, progress/10f).",
            diff="Module-owned settings write WindowManager animation scales 0/1/2. Not a SystemUI hook. A13 and A14 share Helpers.get/setAnimationScale.",
            api33="Same IWindowManager.setAnimationScale Binder on API33.",
            why="Window/transition/animator duration scales still change from the three seekbars.",
            a14_only="none",
            result="Binder setAnimationScale; no Xposed setResult.",
            callback="SeekBar change, not an Xposed callback.",
            args="type 0/1/2 and float value=progress/10.",
            defaults="Seekbars initialize from getAnimationScale; 10 means 1.0x.",
        ),
        _p(
            "PROOF_R5X_AUTOBRIGHTNESS",
            ("system_autobrightness", "system_autobrightness_limitmin", "system_autobrightness_min", "system_autobrightness_limitmax", "system_autobrightness_max"),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemDisplayHooks.kt",
            a14_symbol="AutoBrightnessRangeHook",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemDisplayAndWindowHooks.kt",
            a13_symbol="AutoBrightnessRange / getInt system_autobrightness_min",
            a14_targets="com.android.server.display brightness range members",
            a13_targets="com.android.server.display brightness range members",
            ownership="system_autobrightness_min/max LITERAL_READ in A13 SystemDisplayAndWindowHooks.kt; limitmin/limitmax/master are installer/UI gates in FeatureCatalog.autoBrightnessRange and System_AutoBrightness.kt on both trees.",
            diff="Both clamp automatic brightness using min/max percent. Settings page System_AutoBrightness.kt is shared. A13 catalog id autoBrightnessRange.",
            api33="AOSP DisplayPowerController brightness curve exists on API33. Same min/max percent contract.",
            why="Auto-brightness still respects the min/max percent sliders when the limits are enabled.",
            a14_only="none beyond intercept scaffolding",
            result="Brightness range field/arg rewrite, original compute proceeds.",
            callback="after/intercept on the display brightness owner.",
            args="Percent coerced 0-100; defaults min 25.",
            defaults="Master boolean; min default 25; max from UI; limit toggles default false.",
        ),
        _p(
            "PROOF_R5X_SECUREQS_TILES",
            ("system_secureqs_wifi", "system_secureqs_bt", "system_secureqs_mobiledata", "system_secureqs_airplane", "system_secureqs_location", "system_secureqs_hotspot", "system_secureqs_nfc", "system_secureqs_sync", "system_secureqs_custom"),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemUIControlCenterHooks.kt",
            a14_symbol="SecureQSTilesHook",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemUILockScreenHooks.kt",
            a13_symbol="isSecureTile",
            a14_targets="QSTileImpl#click",
            a13_targets="MiuiQSFactory#createTileInternal / tile#handleClick",
            ownership="Each system_secureqs_* boolean is LITERAL_READ in A13 isSecureTile() and A14 SecureQSTilesHook click path. Parent system_secureqs/keepopened already reviewed.",
            diff="Per-tile booleans select which QS tiles require unlock. Scanner missed them because A13 maps via isSecureTile() not a *Hook named after each key.",
            api33="Same per-tile booleans. Host click member is MIUI14 handleClick vs HyperOS QSTileImpl.click.",
            why="Wifi/bt/cell/airplane/gps/hotspot/nfc/sync/custom tiles still wait for unlock when marked secure.",
            a14_only="longClick/secondaryClick on QSTileImpl",
            result="returnAndSkip until unlock then original click.",
            callback="before skip when locked+secure.",
            args="Skipped click result null.",
            defaults="Each tile boolean default false.",
        ),
        _p(
            "PROOF_R5X_OPENNOTIFY_APPS",
            ("system_notify_openinfw_apps", "system_notify_openinfw_in_whitelist"),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemUINotificationHooks.kt",
            a14_symbol="OpenNotifyInFloatingWindowHook",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemUINotificationHooks.kt",
            a13_symbol="OpenNotifyInFloatingWindowHook",
            a14_targets="StatusBarNotificationActivityStarter#onNotificationClicked",
            a13_targets="MiuiStatusBarNotificationActivityStarter#startNotificationIntent",
            ownership="LITERAL_READ StringSet system_notify_openinfw_apps and boolean _in_whitelist inside OpenNotifyInFloatingWindowHook on both trees (A13 SystemUINotificationHooks.kt:277).",
            diff="Whitelist xor app-set already described on the parent openinfw owner. These rows are the selector/mode, not a second hook.",
            api33="Same StringSet membership test.",
            why="Only selected packages (or all except selected) open notifications in a floating window.",
            a14_only="none for these keys",
            result="No extra rewrite; membership gates the parent hook.",
            callback="Same as parent OpenNotify hook.",
            args="StringSet.contains and whitelist boolean.",
            defaults="Empty set; whitelist default false.",
        ),
        _p(
            "PROOF_R5X_CLOCK_STYLE",
            (
                "system_statusbar_clock_fontsize",
                "system_statusbar_clock_align",
                "system_statusbar_clock_bold",
                "system_statusbar_clock_chip",
                "system_statusbar_clock_chip_usemonet",
                "system_statusbar_clock_chip_orientation_vertical",
                "system_statusbar_clock_chip_startcolor",
                "system_statusbar_clock_chip_endcolor",
                "system_statusbar_clock_chip_customtextcolor",
                "system_statusbar_clock_chip_textcolor",
                "system_statusbar_clock_chip_horizpadding",
                "system_statusbar_clock_chip_verticalpadding",
                "system_statusbar_clock_chip_radius",
                "system_statusbar_clock_leftmargin",
                "system_statusbar_clock_rightmargin",
                "system_statusbar_clock_verticaloffset",
                "system_statusbar_clock_fixedcontent_width",
            ),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemClockHooks.kt",
            a14_symbol="initClockStyle / StatusBarClockTweakHook",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemStatusBarClockAndMoreHooks.kt",
            a13_symbol="initClockStyle",
            a14_targets="status-bar / CC clock TextView style",
            a13_targets="status-bar / CC clock TextView style",
            ownership="LITERAL_READ in A13 initClockStyle (fontsize, chip*, left/right margin). align/bold via interpolated system_${subKey}_clock_align/bold with subKey=statusbar. A14 initClockStyle same family.",
            diff="Style-only TextView mutations on the hooked clock. Scanner missed interpolation keys. Chip drawable colors/padding/radius are the same literals.",
            api33="No extra ROM ABI. Clock TextView styling on MIUI14 vs HyperOS clock controller.",
            why="Status-bar clock size, alignment, bold, chip, margins, and fixed width still apply.",
            a14_only="HyperOS FakeStatusBarClockController path already noted on the parent clock-tweak owner",
            result="View style only; no host result rewrite.",
            callback="after constructor/time hooks then initClockStyle.",
            args="No setResult.",
            defaults="fontsize 13 inactive unless >; align 1; chip false; margins 0; fixed width 10 inactive unless >10.",
        ),
        _p(
            "PROOF_R5X_DEVICEINFO_STYLE",
            (
                "system_statusbar_batterytempandcurrent_fontsize",
                "system_statusbar_batterytempandcurrent_bold",
                "system_statusbar_batterytempandcurrent_align",
                "system_statusbar_batterytempandcurrent_fixedcontent_width",
                "system_statusbar_batterytempandcurrent_leftmargin",
                "system_statusbar_batterytempandcurrent_rightmargin",
                "system_statusbar_batterytempandcurrent_verticaloffset",
                "system_statusbar_showdevicetemperature_fontsize",
                "system_statusbar_showdevicetemperature_bold",
                "system_statusbar_showdevicetemperature_align",
                "system_statusbar_showdevicetemperature_fixedcontent_width",
                "system_statusbar_showdevicetemperature_leftmargin",
                "system_statusbar_showdevicetemperature_rightmargin",
                "system_statusbar_showdevicetemperature_verticaloffset",
            ),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemUIStatusBarHooks.kt",
            a14_symbol="initStatusbarTextIcon",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemUIStatusBarHooks.kt",
            a13_symbol="initStatusbarTextIcon",
            a14_targets="injected status-bar text icon TextView",
            a13_targets="injected status-bar text icon TextView",
            ownership="EXPLICIT_ALIAS via interpolated getInt/getBoolean system_statusbar_${subKey}_* in initStatusbarTextIcon. subKey is batterytempandcurrent or showdevicetemperature. Not XML-only.",
            diff="Both apply fontsize, bold, align, margins, vertical offset, fixed width to the injected battery/temp text icon. Scanner cannot see interpolated keys.",
            api33="Same helper. No ROM member for the style keys.",
            why="Battery-temp and device-temp status-bar text still honor size/bold/align/margins.",
            a14_only="none for these style keys",
            result="TextView style only.",
            callback="Called from icon create/register, not a host skip.",
            args="No setResult.",
            defaults="fontsize 16*0.5 dip path; verticaloffset 8 means no extra top margin; fixed width 10 inactive unless >10; align 1.",
        ),
        _p(
            "PROOF_R5X_SB_LAYOUT",
            (
                "system_statusbarheight",
                "system_statusbar_iconsize",
                "system_statusbar_topmargin_val",
                "system_statusbarcolor",
                "system_statusbarcolor_apps",
                "system_cc_enable_style_switch",
                "system_qs_force_systemfonts",
                "system_recents_disable_wallpaperscale",
            ),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemUIStatusBarHooks.kt",
            a14_symbol="StatusBarHeightConfig / initStatusBarLayout",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemUIStatusBarHooks.kt",
            a13_symbol="StatusBarHeightRes / SystemUIStatusBarHooks layout",
            a14_targets="status_bar_height dimen / status-bar layout",
            a13_targets="status_bar_height dimen / status-bar layout",
            ownership="LITERAL_READ: A13 StatusBarHeightRes getInt(system_statusbarheight,19); SystemUIStatusBarHooks topmargin_val/iconsize/cc_enable_style_switch/qs_force_systemfonts; GenericAppInstaller statusbarcolor+_apps; LauncherInstaller recents_disable_wallpaperscale.",
            diff="Height is a resource replacement (A13 sentinel 19 vs A14 sentinel 11). Icon size, top margin, CC style switch, QS system fonts are live layout reads. Status-bar color is GenericApp per-app hook. Recents wallpaper scale shares DisableLauncherWallpaperScale.",
            api33="status_bar_height overlay exists on API33. Sentinel values differ (19 vs 11) but both mean 'stock until above sentinel'.",
            why="Status-bar height/icon size/top margin/color and CC style/font still apply. Recents wallpaper scale still disabled when the recents toggle is on.",
            a14_only="StatusBarHeightConfig sentinel 11 vs A13 19",
            result="Resource replacement and layout mutation; color hook per app process.",
            callback="Installer-gated resource hook plus layout after inflate.",
            args="No skip of SystemUI constructors beyond documented layout writes.",
            defaults="height sentinel 19 A13 / 11 A14; iconsize 6 inactive unless >; topmargin_val used only when topmargin boolean on.",
        ),
        _p(
            "PROOF_R5X_OPERATOR_NOTIF_NET",
            (
                "system_qs_hideoperator",
                "system_cc_hideoperator_delimiter",
                "system_morenotif",
                "system_networkindicator_wifi",
                "system_lstimeout",
                "system_statusbaricons_clock",
                "system_nooverscroll",
                "system_nooverscroll_apps",
            ),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemSettingsAndConnectivityHooks.kt",
            a14_symbol="HideCCOperatorHook / NetworkIndicator / MoreNotifications",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemSettingsAndConnectivityHooks.kt",
            a13_symbol="HideCCOperatorHook / HideCCOperatorDelimiterHook / MoreNotificationsHook / LockScreenTimeoutHook",
            a14_targets="ControlCenterStatusBar / MiuiCarrierTextController / NetworkSpeed / Notification limits / PhoneWindow userActivityTimeout",
            a13_targets="ControlCenterStatusBar#updateFlaresInfo,MiuiCarrierTextController#fireCarrierTextChanged,MoreNotificationsHook,LockScreenTimeoutHook",
            ownership="INSTALLER_CALLEE SystemUiInstaller: qs_hideoperator→HideCCOperatorHook, cc_hideoperator_delimiter→HideCCOperatorDelimiterHook, morenotif→MoreNotificationsHook, networkindicator_wifi→FeatureCatalog, lstimeout→LockScreenTimeoutHook, statusbaricons_clock→hideIconsClock. nooverscroll+_apps GenericAppInstaller LITERAL_READ.",
            diff="Hide operator GONE on CC/QS carrier TextView. Delimiter strips ' | ' in fireCarrierTextChanged. More notifications raises the shade cap. Wi-Fi network indicator catalog feature. LS timeout writes userActivityTimeout=lstimeout*1000. Clock hide uses hideIconsClock. Overscroll disabled per selected apps.",
            api33="MIUI14 ControlCenterStatusBar/MiuiQSHeaderView vs HyperOS CC package names; delimiter member MiuiCarrierTextController is the A13 ABI.",
            why="CC operator text, delimiter, notification count, Wi-Fi indicator, lock timeout, clock hide, and overscroll still honor these keys.",
            a14_only="HyperOS CC class names for operator hide",
            result="View GONE / string strip / timeout field write / per-app overscroll skip.",
            callback="after GONE; before delimiter rewrite; catalog hide-clock.",
            args="Delimiter rewrites arg0 string; timeout setLongField.",
            defaults="booleans false; lstimeout 3 seconds sentinel; overscroll apps empty.",
        ),
        _p(
            "PROOF_R5X_VIBRATION_AMP",
            ("system_vibration_amp", "system_vibration_amp_period_start", "system_vibration_amp_period_end"),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemAudioAndVisualAndMoreHooks.kt",
            a14_symbol="MuffledVibrationHook",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemAudioAndVisualAndMoreHooks.kt",
            a13_symbol="MuffledVibrationHook",
            a14_targets="VibratorService#doVibratorOn",
            a13_targets="com.android.server.VibratorService#doVibratorOn",
            ownership="system_vibration_amp INSTALLER_CALLEE FeatureCatalog.muffledVibration. Period start/end: A13 concatenates system_vibration_amp_period + _start/_end in MuffledVibrationHook; settings page System_VibrationAmp.kt. A14 reads the same period keys.",
            diff="Scanner missed concatenated period keys. Master boolean installs the amplitude scaler. Quiet-window hours come from period_start/end.",
            api33="Same doVibratorOn arg scale. Concatenation vs literal getInt is A13 key-build, not a ROM gap.",
            why="Vibration amplitude still scales inside the quiet period defined by start/end.",
            a14_only="none",
            result="Amplitude/duration args scaled; original proceeds.",
            callback="before arg rewrite vs intercept proceed(args).",
            args="args[1] amplitude or args[0] duration.",
            defaults="Master false; period defaults 0.",
        ),
        _p(
            "PROOF_R5X_CALLUI_NIGHT",
            ("various_calluibright_night_start", "various_calluibright_night_end"),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/Various.kt",
            a14_symbol="CallUIBrightnessHook",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/Various.kt",
            a13_symbol="CallUIBrightnessHook",
            a14_targets="InCallUI brightness window",
            a13_targets="InCallUI brightness window",
            ownership="A13 concatenates various_calluibright_night + _start/_end (Various.kt:1049). Settings Various_CallUIBright.kt uses pref_key_various_calluibright_night_. PhoneInstaller gates on various_calluibright.",
            diff="Night window hours are helpers of Call UI brightness, not a separate ROM ABI. Scanner missed concatenation.",
            api33="Same InCallUI brightness owner.",
            why="Call-screen brightness still uses the night start/end window when type selects night mode.",
            a14_only="none",
            result="Brightness write uses the resolved window; no extra host skip.",
            callback="Same Call UI brightness hook.",
            args="No extra result rewrite for these keys.",
            defaults="Start/end default 0 in the concatenated ints.",
        ),
        _p(
            "PROOF_R5X_SETTINGS_SHORTCUTS",
            (
                "various_aospnotif",
                "various_batteryoptimization",
                "various_runningservices",
                "various_allow_untrusted_touch",
                "system_credentials",
                "system_applock_list",
                "system_batteryindicator_test",
                "system_cleanshare_test",
                "system_cleanopenwith_test",
            ),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/subs/Various_HiddenFeatures.kt",
            a14_symbol="hidden-feature shortcuts / System.kt test clicks",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/subs/Various_HiddenFeatures.kt",
            a13_symbol="Various_HiddenFeatures / System.kt / Various.kt",
            a14_targets="(no ROM hook; Settings intents / component enable / test intents)",
            a13_targets="(no ROM hook; Settings intents / component enable / test intents)",
            ownership="Click handlers: Various_HiddenFeatures.kt AOSP notification/battery-optimization/running-services intents. various_allow_untrusted_touch writes Settings.Global block_untrusted_touches 0/2 in subs/Various.kt. system_credentials enables CredentialsLauncher component. applock_list/batteryindicator_test/cleanshare_test/cleanopenwith_test are settings pickers/test intents in subs/System.kt and System_BatteryIndicator.kt. Same files exist on A14.",
            diff="These rows are module Settings UI, not host hooks. AOSP shortcuts, untrusted-touch global, credentials activity, applock picker, and share/open-with/battery-indicator test clicks match on both trees.",
            api33="Settings.Global.block_untrusted_touches exists on API33. CredentialsLauncher is in-module. Test intents do not require ROM members.",
            why="Tapping the rows still opens the same Settings pages, toggles untrusted touch, enables the credentials launcher, edits applock apps, or fires the share/open-with/indicator tests.",
            a14_only="none for these UI rows",
            result="startActivity / setComponentEnabledSetting / Settings.Global.putInt. No Xposed setResult.",
            callback="Preference click/change, not an Xposed callback.",
            args="n/a",
            defaults="Credentials off; untrusted-touch follows the checkbox; test rows are click-only.",
        ),
        _p(
            "PROOF_R5X_NO_ACCESS_LOGS",
            ("various_disable_access_devicelogs",),
            a14_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemDisplayHooks.kt",
            a14_symbol="NoAccessDeviceLogsRequest",
            a13_path="app/src/main/java/tv/withaibuild/customiuizer/mods/SystemDisplayAndWindowHooks.kt",
            a13_symbol="NoAccessDeviceLogsRequest",
            a14_targets="device-log access confirmation members",
            a13_targets="device-log access confirmation members",
            ownership="INSTALLER_CALLEE A13 SystemServerInstaller.java:98 FeatureDispatcher noAccessDeviceLogsRequest; FeatureCatalog preferenceKeys various_disable_access_devicelogs. A14 SystemServer feature same key.",
            diff="Both skip/allow the device-logs access prompt via NoAccessDeviceLogsRequest. Catalog contract vs FeatureSpec.",
            api33="AOSP device-log permission prompt exists on API33. CatalogContracts.noAccessDeviceLogsRequest lists the A13 members.",
            why="Apps no longer get the device-logs access prompt when the toggle is on.",
            a14_only="none beyond intercept scaffolding",
            result="Prompt path skipped or forced allow per the catalog member.",
            callback="before skip vs intercept skip.",
            args="Skip original prompt.",
            defaults="Boolean default false keeps the ROM prompt.",
        ),
    ]
